# Generated by Django 5.1.7 on 2025-08-16 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_chambre_numero_remove_hotel_adresse_and_more'),
        ('reserve', '0002_chambre_alter_reservation_statut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='chambre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.chambre'),
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
    ]
