# Generated by Django 5.1.7 on 2025-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decouverte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='decouvertes/')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('auteur', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
