# Generated by Django 5.1.7 on 2025-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_decouverte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='publicites/')),
                ('lien', models.URLField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
