# Generated by Django 5.1.7 on 2025-08-16 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_publicite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Publicite',
        ),
        migrations.DeleteModel(
            name='Chambre',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
