# Generated by Django 5.1.7 on 2025-08-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_chambre_hotel_delete_publicite_delete_chambre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='publicites/')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
