# Generated by Django 5.1.7 on 2025-08-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='prix_par_nuit',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='type',
        ),
        migrations.AddField(
            model_name='chambre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chambres/'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='nom',
            field=models.CharField(default='Chambre1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='prix_nuit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hotel',
            name='type_hotel',
            field=models.CharField(default='standart', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
