# Generated by Django 5.1.7 on 2025-08-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_chambre_numero_remove_hotel_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(default='Chambre1', max_length=100),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='type_chambre',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Suite', 'Suite'), ('Deluxe', 'Deluxe')], default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='type_hotel',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Residence', 'Residence')], default='Hotel', max_length=50),
        ),
    ]
